# Gemfile
source 'https://rubygems.org'

gem 'sinatra', '>= 2.2.0'
gem 'sinatra-contrib', '>= 2.2.0'
gem 'sinatra-cross_origin', '~> 0.3.1'
gem 'mongoid'

group :test, :development do
  gem 'faker'
  gem 'airborne', '>= 0.3.4'
  gem 'rspec'
  gem 'rspec_junit_formatter'
end
